name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kind cluster
        uses: ./

      - name: Test
        run: |
          kubectl cluster-info
          kubectl get storageclass standard

  test-with-custom-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kind cluster with custom vars
        uses: helm/kind-action@$GITHUB_SHA
        with:
          cluster_name: "custom-name"
          config: ./tests/config.yaml
          wait: 61s
          log_level: DEBUG
          

      - name: Test
        run: |
          kubectl cluster-info
          kubectl get storageclass standard
